SELECT  *
FROM    TB_DEPARTMENT
--1번.
SELECT  DEPARTMENT_NAME AS 학과명,
        CATEGORY AS 계열
FROM    TB_DEPARTMENT;
--2번
SELECT  DEPARTMENT_NAME||'의 정원은 '||CAPACITY||'명 입니다.'
FROM    TB_DEPARTMENT

--3번
SELECT  STUDENT_NAME
FROM    TB_STUDENT
WHERE   ABSENCE_YN = 'Y' AND STUDENT_SSN LIKE ('_______2______') AND DEPARTMENT_NO = '001';

--4번 
SELECT  STUDENT_NAME
FROM    TB_STUDENT
WHERE   STUDENT_NO IN ('A513079','A513090','A513091','A513110','A513119');

--5번
SELECT  DEPARTMENT_NAME,
        CATEGORY
FROM    TB_DEPARTMENT
WHERE   CAPACITY BETWEEN 20 AND 30;

--6번
SELECT  PROFESSOR_NAME
FROM    TB_PROFESSOR
WHERE   DEPARTMENT_NO IS NULL;

--7번
SELECT  STUDENT_NAME
FROM    TB_STUDENT
WHERE   DEPARTMENT_NO IS NULL;

--8번
SELECT  CLASS_NO
FROM    TB_CLASS
WHERE   PREATTENDING_CLASS_NO IS NOT NULL;

--9번
SELECT  DISTINCT CATEGORY
FROM    TB_DEPARTMENT;

--10번
SELECT  STUDENT_NO,
        STUDENT_NAME,
        STUDENT_SSN
FROM    TB_STUDENT
WHERE   STUDENT_ADDRESS LIKE ('전주%') AND ABSENCE_YN = 'N';
--
--[ADDITIONAL SELECT 함수]
--1번
SELECT  STUDENT_NO AS 학번,
        STUDENT_NAME AS 이름,
        TO_CHAR(ENTRANCE_DATE,'YYYY-MM-DD') AS 입학년도
FROM    TB_STUDENT
WHERE   DEPARTMENT_NO = '002' ORDER BY 3;

--2번
SELECT  PROFESSOR_NAME,
        PROFESSOR_SSN
FROM    TB_PROFESSOR
WHERE   PROFESSOR_NAME NOT LIKE '___'; -- LENGTH(PROFESSOR_NAME) != 3

--3번
SELECT  PROFESSOR_NAME AS 교수이름,
        FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE('19'||SUBSTR(PROFESSOR_SSN,1,6),'RRRRMMDD')) / 12) AS 나이
FROM    TB_PROFESSOR
WHERE   SUBSTR(PROFESSOR_SSN,8,1) = '1' ORDER BY 2;

--4번
SELECT  SUBSTR(PROFESSOR_NAME,2) AS 이름
FROM    TB_PROFESSOR

--5번
SELECT  STUDENT_NO,
        STUDENT_NAME
FROM    TB_STUDENT
WHERE   FLOOR(MONTHS_BETWEEN(ENTRANCE_DATE,TO_DATE('19'||SUBSTR(STUDENT_SSN,1,6),'RRRRMMDD'))/12) > 19

--6번
SELECT  TO_CHAR(TO_DATE(20201225),'DAY')
FROM    DUAL;

--7번
SELECT  TO_DATE('99/10/11','YY/MM/DD')
        TO_DATE('49/10/11','YY/MM/DD'),
        TO_DATE('99/10/11','RR/MM/DD'),
        TO_DATE('49/10/11','RR/MM/DD')
FROM    DUAL;

--8번
SELECT  STUDENT_NO,
        STUDENT_NAME
FROM    TB_STUDENT
WHERE   STUDENT_NO NOT LIKE 'A%' ;

--9번
SELECT  ROUND(AVG(POINT),1) AS 평점
FROM    TB_GRADE
WHERE   STUDENT_NO = 'A517178';

--10번
SELECT  DEPARTMENT_NO,
        COUNT(*) "학생수(명)"
FROM    TB_STUDENT
GROUP BY    DEPARTMENT_NO
ORDER BY    1;

--11번
SELECT  COUNT(*)
FROM    TB_STUDENT
WHERE   COACH_PROFESSOR_NO IS NULL

--12번
SELECT  SUBSTR(TERM_NO,1,4) 년도,
        ROUND(AVG(POINT),1) "년도 별 평점"
FROM    TB_GRADE
WHERE   STUDENT_NO = 'A112113'
GROUP BY    SUBSTR(TERM_NO,1,4)
ORDER BY 1;

--13
SELECT  DEPARTMENT_NO 학과코드명,
        COUNT(DECODE(ABSENCE_YN,'Y','Y')) "휴학생 수"
FROM    TB_STUDENT
GROUP BY    DEPARTMENT_NO
ORDER BY    1;

--14
SELECT  STUDENT_NAME 동일이름,
        COUNT(*) "동명인 수"
FROM    TB_STUDENT
GROUP BY    STUDENT_NAME
HAVING  COUNT(*) > 1
ORDER BY    1;

--15
SELECT  SUBSTR(TERM_NO,1,4) 년도,
        SUBSTR(TERM_NO,5,2) 학기,
        ROUND(AVG(POINT),1) 평점
FROM    TB_GRADE
WHERE   STUDENT_NO = 'A112113'
GROUP BY    ROLLUP(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2))

--16번
SELECT  CLASS_NO,
        CLASS_NAME,
        ROUND(AVG(POINT),8)
FROM    TB_CLASS
JOIN    TB_GRADE USING(CLASS_NO)
WHERE   DEPARTMENT_NO = '034' AND CLASS_TYPE LIKE '전공%'
GROUP BY    CLASS_NO, CLASS_NAME;

--17번
SELECT  STUDENT_NAME,
        STUDENT_ADDRESS
FROM    TB_STUDENT
JOIN    TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE   DEPARTMENT_NO IN(SELECT DEPARTMENT_NO
                         FROM   TB_STUDENT
                         WHERE  STUDENT_NAME LIKE '최경희');

--18번
SELECT  STUDENT_NO,
        STUDENT_NAME
FROM    TB_STUDENT
JOIN    TB_GRADE USING(STUDENT_NO)
WHERE   DEPARTMENT_NO = '001'
GROUP BY STUDENT_NO, STUDENT_NAME
HAVING  AVG(POINT) = (SELECT    MAX(AVG(POINT))
                        FROM    TB_GRADE
                        JOIN    TB_STUDENT USING(STUDENT_NO)
                        WHERE   DEPARTMENT_NO = '001'
                        GROUP BY    STUDENT_NO);

--19번
SELECT  CATEGORY
FROM    TB_DEPARTMENT
WHERE   DEPARTMENT_NAME = '환경조경학과'
-- CATEGORY : 자연과학

SELECT  DEPARTMENT_NAME "계열 학과명",
        ROUND(AVG(POINT),1) "전공 평점"
FROM    TB_DEPARTMENT D
JOIN    TB_CLASS C ON(D.DEPARTMENT_NO = C.DEPARTMENT_NO)
JOIN    TB_GRADE G ON(G.CLASS_NO = C.CLASS_NO)
WHERE   CATEGORY = (SELECT  CATEGORY
                    FROM    TB_DEPARTMENT
                    WHERE   DEPARTMENT_NAME LIKE '환경조경학과')
AND     CLASS_TYPE IN (SELECT   CLASS_TYPE
                        FROM    TB_CLASS
                        WHERE   CLASS_TYPE LIKE '전공%')
GROUP BY    DEPARTMENT_NAME
